openapi: 3.0.3
info:
  title: Healthcare AI Assistant MCP API
  version: 1.0.0
  description: >
    Secure, HIPAA-compliant healthcare API for Cequence AI Gateway and MCP agents.
servers:
  - url: https://localhost:8000
    description: Development server
  - url: https://healthcare-mcp.fly.dev
    description: Production server
security:
  - oauth2:
      - patient.read
      - appointment.write
      - insurance.verify
      - care.coordinate
paths:
  /api/v1/patient-data:
    post:
      summary: Retrieve FHIR patient data
      description: Retrieve patient medical records and demographics from Epic/Cerner FHIR servers.
      operationId: getPatientData
      tags:
        - Patient Data
      security:
        - oauth2: [patient.read]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDataRequest'
      responses:
        '200':
          description: Patient data response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientData'
        '401':
          description: Unauthorized – invalid token
        '403':
          description: Forbidden – insufficient scope
        '404':
          description: Patient not found

  /api/v1/appointment:
    post:
      summary: Schedule appointment
      description: Schedule an appointment with a healthcare provider via the EHR system.
      operationId: scheduleAppointment
      tags:
        - Appointments
      security:
        - oauth2: [appointment.write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentRequest'
      responses:
        '201':
          description: Appointment scheduled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/v1/drug-interactions:
    post:
      summary: Check drug interactions
      description: Analyze potential interactions using RxNorm and FDA data.
      operationId: checkDrugInteractions
      tags:
        - Medications
      security:
        - oauth2: [patient.read]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DrugInteractionRequest'
      responses:
        '200':
          description: Interaction analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrugInteractionResponse'
        '400':
          description: Bad request

  /api/v1/insurance-eligibility:
    post:
      summary: Verify insurance eligibility
      description: Check patient insurance via X12 EDI 270/271.
      operationId: verifyInsuranceEligibility
      tags:
        - Insurance
      security:
        - oauth2: [insurance.verify]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsuranceEligibilityRequest'
      responses:
        '200':
          description: Eligibility response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsuranceEligibilityResponse'
        '400':
          description: Bad request

  /api/v1/referral:
    post:
      summary: Create referral
      description: Create specialist referral and coordinate patient care.
      operationId: createReferral
      tags:
        - Care Coordination
      security:
        - oauth2: [care.coordinate]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReferralRequest'
      responses:
        '201':
          description: Referral created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferralResponse'
        '400':
          description: Bad request

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.descope.com/v1/oauth2/auth
          tokenUrl: https://api.descope.com/v1/oauth2/token
          scopes:
            patient.read: Read patient medical records
            appointment.write: Schedule appointments
            insurance.verify: Verify insurance eligibility
            care.coordinate: Coordinate patient care
  schemas:
    PatientDataRequest:
      type: object
      required:
        - patient_id
        - fhir_server_url
        - access_token
      properties:
        patient_id:
          type: string
          example: "12345"
        fhir_server_url:
          type: string
          example: "https://fhir.epic.com/interconnect-fhir-oauth"
        access_token:
          type: string
    PatientData:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        birth_date:
          type: string
          format: date
        gender:
          type: string
        conditions:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              description:
                type: string
        medications:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              name:
                type: string
              dosage:
                type: string
        allergies:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              substance:
                type: string
              reaction:
                type: string
    AppointmentRequest:
      type: object
      required:
        - patient_id
        - provider_id
        - appointment_time
      properties:
        patient_id:
          type: string
        provider_id:
          type: string
        appointment_time:
          type: string
          format: date-time
        reason:
          type: string
        location:
          type: string
    AppointmentResponse:
      type: object
      properties:
        appointment_id:
          type: string
        status:
          type: string
    DrugInteractionRequest:
      type: object
      required:
        - medications
      properties:
        medications:
          type: array
          items:
            type: string
    DrugInteractionResponse:
      type: object
      properties:
        interactions:
          type: array
          items:
            type: object
            properties:
              drug_a:
                type: string
              drug_b:
                type: string
              severity:
                type: string
              description:
                type: string
        recommendations:
          type: array
          items:
            type: string
    InsuranceEligibilityRequest:
      type: object
      required:
        - patient_id
        - insurance_info
      properties:
        patient_id:
          type: string
        insurance_info:
          type: object
    InsuranceEligibilityResponse:
      type: object
      properties:
        patient_id:
          type: string
        insurance_id:
          type: string
        eligible:
          type: boolean
        plan_name:
          type: string
        coverage_details:
          type: string
        copay:
          type: number
        deductible:
          type: number
    ReferralRequest:
      type: object
      required:
        - patient_id
        - referring_provider
        - specialist_provider
        - reason
      properties:
        patient_id:
          type: string
        referring_provider:
          type: string
        specialist_provider:
          type: string
        reason:
          type: string
        urgency:
          type: string
          enum:
            - routine
            - urgent
            - emergent
        preferred_location:
          type: string
    ReferralResponse:
      type: object
      properties:
        referral_id:
          type: string
        status:
          type: string
